### ISSUE TITLE
Failed to build elynx-tree

### ISSUE THREAD

**Issue by rvyhvn** [dschrempf/elynx#4]
src/ELynx/Tree/Rooted.hs:173:3: error:
    ‘liftA2’ is not a (visible) method of class ‘Applicative’
    |
173 |   liftA2 f ~(Node brX lbX tsX) ~ty@(Node brY lbY tsY) =
    |   ^^^^^^

src/ELynx/Tree/Rooted.hs:458:3: error:
    ‘liftA2’ is not a (visible) method of class ‘Applicative’
    |
458 |   liftA2 f (BranchTree ~(Node brX lbX tsX)) ty@(BranchTree ~(Node brY lbY tsY)) =
    |   ^^^^^^

src/ELynx/Tree/Rooted.hs:521:3: error:
    ‘liftA2’ is not a (visible) method of class ‘Applicative’
    |
521 |   liftA2 f (ZipTree ~(Node brX lbX tsX)) (ZipTree ~(Node brY lbY tsY)) =
    |   ^^^^^^

src/ELynx/Tree/Rooted.hs:583:3: error:
    ‘liftA2’ is not a (visible) method of class ‘Applicative’
    |
583 |   liftA2 f (ZipBranchTree ~(Node brX lbX tsX)) (ZipBranchTree ~(Node brY lbY tsY)) =
    |   ^^^^^^

**Comment by dschrempf** [comment]
Hi! Thanks for your interest in `elynx-tree`! Could you please be a bit more specific? Which version of GHC are you using? Are you compiling with `stack` or `cabal`?

**Comment by rvyhvn** [comment]
my bad, sorry. i didn't use ghc with the LTS version. i was using ghc version 9.4.8, now it works with `cabal build elynx`. issue closed.

**Comment by dschrempf** [comment]
Thanks!
